### ISSUE TITLE
Feature request- merge into paper-button repo

### ISSUE THREAD

**Issue by dman777** [PolymerElements/paper-fab#32]
Sine this is a button, can it placed in paper-button repo? I had a hard time finding this. Or re-titled to `paper-action-button` so it would show up in a search for button?

**Comment by notwaldorf** [comment]
I think both of these approaches would break a lot of people that are currently using `<paper-fab>` in their applications, so it's unlikely they can happen at this point. We've added a bunch of better words in the docs that should help with SEO, and the button is tagged correctly in the catalog (https://elements.polymer-project.org/browse?tag=button&package=paper-elements), so I think this is the best we can do at this point :(

/cc @cdata @tjsavage

**Comment by tjsavage** [comment]
Hm yeah it's too bad this was hard to find, thanks @notwaldorf for the SEO updates. The most common feedback we've seen is that elements are harder to find when they are combined into the same repo, as the expectation is for the element name to match the repo name. Because of this, as well as to minimize unnecessary local files, we generally prefer granularity over combining. 

Re-naming to `paper-floating-action-button` would be more clear, but I think better keywords on the repo and element should have the same positive impact on searchability, and `paper-floating-action-button` is a bit long to type. Point well taken though - we can improve searchability both on search engines and in the catalog.

**Comment by notwaldorf** [comment]
SEO updates were all @ebidel (links to material design, etc):)
