### ISSUE TITLE
Ideogram support

### ISSUE THREAD

**Issue by naoak** [PolymerElements/paper-fab#56]
In our culture region, we use ideograms in writing. Sometimes, an ideogram represents its mean more explicitly and concisely than an icon.

We can show any characters on fab with deep selector.
![heart](https://cloud.githubusercontent.com/assets/1264530/12472850/9ea5c928-c04f-11e5-8988-6fcf36df977f.png)

But, it would be nice if paper-fab had the following custom properties.

```
iron-icon:before {
  @apply(--paper-fab-iron-icon-before);
}
``` 

```
iron-icon:after {
  @apply(--paper-fab-iron-icon-after);
}
``` 

If you would like it, I'll make the PR.

**Comment by naoak** [comment]
Sorry, --paper-fab-iron-icon is right in screenshot.

**Comment by notwaldorf** [comment]
The `/deep/` combinator is getting deprecated (and it's not recommended in general), so that definitely won't work. However, we can pass in a `String` attribute that would be used instead of the icon:
```
<paper-fab label="foo"></paper-fab>
```

And in the implementation of `paper-fab`,
```
<span>{{label}}</span>
```

It would be nice if we could also truncate this label to max 2 characters (you can check out `paper-badge`, which has a similar feature)

Would you be interested in submitting a patch for this?

**Comment by naoak** [comment]
Sounds like a great idea! I know that `paper-badge` exists, but have never used it. I don't know whether I can create a good enough patch to be accepted, but anyway, I'll try it.:stuck_out_tongue:

Thank you for leading in the right direction!

**Comment by notwaldorf** [comment]
Don't worry! We'll work through the patch together and get it right! Let me know whenever you have any questions :)

**Comment by naoak** [comment]
Thanks :)

**Comment by notwaldorf** [comment]
Fixed in https://github.com/PolymerElements/paper-fab/pull/60
